#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -xe

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect("${DATABASE_URL}")
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo '💽 PostgreSQL is available'

python manage.py migrate --noinput
python manage.py collectstatic --noinput --clear
gunicorn blog_cms.wsgi:application --log-level error
